-- ==========================================
-- INSERT SCRIPT FOR SST PRODUCTS
-- ==========================================

INSERT INTO public.products (company, product_code, name, price, unit, barcode) VALUES
('SST', '884', 'TS-0884 Memory 8Mb For 4DC, 4LC', 0, 'EACH', ''),
('SST', '100310-670006 VP1-3', 'Euro Mortice Lock 60 mm.', 0, 'EACH', ''),
('SST', '1084', 'TS-1084 Momory 8Mb For C10', 0, 'EACH', ''),
('SST', '40KNKS-00-000', 'HID Signo 40 Standard Profile with keypa', 0, 'EACH', ''),
('SST', '40NKS', '40NKS-TO-00021G', 0, 'EACH', ''),
('SST', '42EU', 'Control Unit Online Update', 26700, 'Unit', ''),
('SST', '45515', 'ECO UMCO FULL-Color Refill', 1800, 'Unit', ''),
('SST', '5427', 'HID USB Reader', 0, 'EACH', ''),
('SST', '724SRSIL', 'Door Closer Slide Arm Size4', 0, 'EACH', ''),
('SST', '726SRSIL', 'Lockwood Size6, Silding Arm', 0, 'EACH', ''),
('SST', '90246106', 'LEV HDL W/OVAL', 600, 'Unit', ''),
('SST', '90300178', 'Pull Handle Stanless', 0, 'EACH', ''),
('SST', '90392616', 'PC HANDLE SET', 0, 'EACH', ''),
('SST', '90946106', 'Spindle ด้านเดียว', 330, 'EACH', ''),
('SST', '91122546', 'Mortice Lock Set Deadbolt', 0, 'EACH', ''),
('SST', '91126292', 'Mortise lock for sliding door', 900, 'EACH', ''),
('SST', '91175023', 'Hafele Narrow Profile Lock Case', 2130, 'Unit', ''),
('SST', '91176011', 'Strike Plate', 510, 'Unit', ''),
('SST', '91600600', 'Hafele Cylinder 40 mm.', 1200, 'EACH', ''),
('SST', '91600604', 'Hafele Cylinder 40 mm.', 1200, 'EACH', ''),
('SST', 'A590SC', 'A590SC Lockwood Swing Door', 0, 'EACH', ''),
('SST', 'A591SC', 'A591SC Lockwood Swing Door', 0, 'EACH', ''),
('SST', 'A9658L62IM38', 'SALTO XS4 Eletronic Escutcheon Ax658', 0, 'EACH', ''),
('SST', 'A9660U001', 'XS4 HALF ESCUTCHEON Ax650', 15000, 'EACH', ''),
('SST', 'A9660000IMH8', 'XS4 Half Escutcheon Ax650 for panic ba', 15000, 'Unit', ''),
('SST', 'AA51036072-F', 'Mortise Lock Euro 60 mm', 0, 'EACH', ''),
('SST', 'ACT591CTSC', 'Narrow profile lock case sliding', 0, 'EACH', ''),
('SST', 'ACT592CTSC', 'Narrow profile lock case swing', 0, 'EACH', ''),
('SST', 'AE90IMWG3A8', 'SALTO Aelement electronics without ele', 0, 'EACH', ''),
('SST', 'ΑΕΡ-010', 'Cylinder Cover', 0, 'EACH', ''),
('SST', 'AFBOIMSET', 'ALEMENT FUSION SAMPLE MOCKUP', 0, 'Unit', ''),
('SST', 'AFB4IMB3A8', 'Salto Alement Fusion BLE', 0, 'EACH', ''),
('SST', 'BA-01', 'อุปกรณ์ Wifi', 0, 'EACH', ''),
('SST', 'Battery CR2', 'Battery', 0, 'EACH', ''),
('SST', 'BEP2', 'Suprema BEP2', 0, 'EACH', ''),
('SST', 'BEW2ODP', 'Suprema BEW2- Outdoor IP67', 0, 'EACH', ''),
('SST', 'BG', 'Glass Bracket for Magnetic Lock', 0, 'EACH', ''),
('SST', 'BR535-001', 'Aluminum Streight Arm For Automatice', 0, 'EACH', ''),
('SST', 'BR655', 'Barrier with Arm SM', 0, 'EACH', ''),
('SST', 'Bracket', 'Bracket for Aluminium door', 0, 'EACH', ''),
('SST', 'BracketDSU-60', 'Glass Blacket for Magnetic Lock', 0, 'EACH', ''),
('SST', 'BSB110BXBT', 'BSB110BXBT SCHNEIDER BREAKER', 0, 'Unit', ''),
('SST', 'BZ', 'Buzzer', 0, 'EACH', ''),
('SST', 'C6N2MP', 'กล้อง', 0, 'EACH', ''),
('SST', 'CAP10UF', 'CAO 10UF', 0, 'EACH', ''),
('SST', 'CARD', 'EM Card', 0, 'CARD', ''),
('SST', 'Card-duo', 'Card Mifare&Em', 0, 'EACH', ''),
('SST', 'Carparksystem', 'Barrier Carpark Entrancel1 Cont', 0, 'Jobs', ''),
('SST', 'CE1T1AL30IM', 'Striker Plate', 0, 'EACH', ''),
('SST', 'CE8P', 'Strike Plate', 0, 'EACH', ''),
('SST', 'CE8POR', 'Striker Plate', 0, 'EACH', ''),
('SST', 'CE8P1CS3', 'SALTO Squared strike plate with straight', 0, 'EACH', ''),
('SST', 'CEGD', 'Strike plate for glass frames', 0, 'EACH', ''),
('SST', 'COVER', 'Cylinder Cover', 0, 'EACH', ''),
('SST', 'CSC6NR101', 'กล้อง', 0, 'EACH', ''),
('SST', 'CSH8C', 'กล้อง', 0, 'EACH', ''),
('SST', 'CU41BOTUS', 'Salto KS Controller', 0, 'EACH', ''),
('SST', 'CU41BY', 'SALTO CONTROL UNIT Black Finish', 0, 'EACH', ''),
('SST', 'CU41BYUS', 'Control Unit KS US Black', 0, 'EACH', ''),
('SST', 'CU41WY', 'Salto Control Unit White', 0, 'EACH', ''),
('SST', 'CU42', 'Salto Control Unit', 0, 'EACH', ''),
('SST', 'CU4200', 'SALTO XS4 2.0 ethernet control unit, off', 0, 'EACH', ''),
('SST', 'CU42E0', 'SALTO XS4 2.0 ETHERNET CONTROL', 0, 'Unit', ''),
('SST', 'CU42EN', 'SALTO Online Main Control Unit', 0, 'EACH', ''),
('SST', 'CU5000', 'SALTO proximity card encoder Mifare/D', 0, 'EACH', ''),
('SST', 'E90290921M3', 'Electronic Escutheon, Security', 0, 'EACH', ''),
('SST', 'E9150', 'SALTO XS4 Mini Escutcheon Ex150 BLE', 0, 'EACH', ''),
('SST', 'E9150WRIMB38', 'Salto electr. XS4 Mini', 0, 'EACH', ''),
('SST', 'E9450', 'XS4 Escutcheon Wireless', 0, 'Unit', ''),
('SST', 'E9451L85IM3', 'SALTO XS4 Electronic Escutcheon Ex45', 0, 'EACH', ''),
('SST', 'E9451U851M38', 'Escutcheon Mifare', 0, 'EACH', ''),
('SST', 'E9650', 'SALTO XS4 ESCUTCHEON WIDE WIREL', 0, 'EACH', ''),
('SST', 'E9650W', 'SALTO Escutcheong wide plate, Wireless', 0, 'EACH', ''),
('SST', 'E9654U85IM38', 'SALTO XS4 Electr. Escutcheon Ex454-W', 15500, 'EACH', ''),
('SST', 'E96P0LGDIMOL', 'Electronic Escutcheon Glass', 0, 'EACH', ''),
('SST', 'E9750L00IMB3', 'Salto Electr. escutcheon Mifare', 0, 'EACH', ''),
('SST', 'E9CD0000IM', 'Electronic escutcheon Mifare', 0, 'EACH', ''),
('SST', 'EA028L55IM4', 'SALTO Security Electronic Escutcheon E', 0, 'EACH', ''),
('SST', 'EB150LRIMB38', 'SALTO XS4 Mini', 0, 'EACH', ''),
('SST', 'EB150URIMB38', 'SALTO XS4 Mini BLE escutcheon', 0, 'EACH', ''),
('SST', 'EB150WRIMB3', 'Salto XS4 MINI', 0, 'EACH', ''),
('SST', 'EB450U00IM38', 'Electr, escutcheon Mifare', 0, 'EACH', ''),
('SST', 'EB450U00IM39', 'SALTO XS4 BLE escutcheon, IM Finish', 0, 'EACH', ''),
('SST', 'EB5008', 'SALTO Relay extension board (8 relays)', 0, 'EACH', ''),
('SST', 'EB650U00IMH8SALTO', 'XS4 for Panic Online with keypad', 0, 'EACH', ''),
('SST', 'EB751', 'XS4 One Mifare BLB', 0, 'EACH', ''),
('SST', 'EB94510851A3', 'SALTO XS4 Electronic Escutcheon Ex45', 0, 'EACH', ''),
('SST', 'EBG', 'Emergency Break Glass', 0, 'EACH', ''),
('SST', 'EBG-GSB', 'Breakglass Glass-Soild', 0, 'EACH', ''),
('SST', 'EBG-GST', 'Breakglass Glass-Transparet', 0, 'EACH', ''),
('SST', 'EBK-900C', 'Breakglass firm emergency', 970, 'Unit', ''),
('SST', 'EBK-902', 'Uninterrupted power supply controller', 2690, 'Unit', ''),
('SST', 'EBP', 'EMERGENCY EXIT BUTTON', 0, 'EACH', ''),
('SST', 'EC904B0', 'NCoder-Proximity card encoder', 0, 'EACH', ''),
('SST', 'EC90EN', 'ENCODER Ethernet', 0, 'EACH', ''),
('SST', 'EC90USB', 'SALTO proximity card encoder Mifare/D', 0, 'EACH', ''),
('SST', 'ECB04B0', 'SALTO ENCODER', 0, 'EACH', ''),
('SST', 'ECB04B0EU', 'Salto Encoder', 0, 'EACH', ''),
('SST', 'ECB04D0', 'NCoder - Proximity Card encoder', 0, 'EACH', ''),
('SST', 'ECB-535', 'End Cap big for Barrier arm', 0, 'EACH', '');

INSERT INTO public.products (company, product_code, name, price, unit, barcode) VALUES
('SST', 'ECD92UI', 'SALTO Energy Saver ESD9000', 0, 'EACH', ''),
('SST', 'ECS-535', 'End cap Small for Barrier arm', 0, 'EACH', ''),
('SST', 'EL560SET', 'ABloy Mortise Lock', 0, 'EACH', ''),
('SST', 'EM150LRIMB38', 'Salto XS4 Mini', 0, 'EACH', ''),
('SST', 'EM-290T', 'Single door magnet lock with LED&time', 2370, 'Unit', ''),
('SST', 'EM450000IMB3', 'SALTO XS4+ Escutcheon, EURO, U Hand', 0, 'EACH', ''),
('SST', 'EM450U00IMB', 'SALTO XS4 for Panic Wireless Online', 0, 'EACH', ''),
('SST', 'EM450U00IMB', 'SALTO XS4 for Panic Offline', 0, 'EACH', ''),
('SST', 'EM450URIMB3', 'SALTO XS4 escutcheon', 0, 'EACH', ''),
('SST', 'EM650U00IMB3', 'SALTO XS4 escutcheon', 0, 'EACH', ''),
('SST', 'EM850U00IMB3', 'SALTO XS4', 0, 'EACH', ''),
('SST', 'EM9100', 'Medium Range Reader 60-90 СМ.', 0, 'EACH', ''),
('SST', 'EMISO', 'EM Card', 0, 'EACH', ''),
('SST', 'EMK-280ZL', 'THE ZL bracket is for inward door', 760, 'Unit', ''),
('SST', 'EML', 'Magnetic lock 600 lbs with Led', 0, 'EACH', ''),
('SST', 'EMLDH', 'Magnetic Door Holder', 0, 'EACH', ''),
('SST', 'EN90USB', 'SALTO Encorder USB', 0, 'EACH', ''),
('SST', 'EnrollUSB', 'Suprema Enroll USB', 0, 'EACH', ''),
('SST', 'ENTFG800', 'ไม้กั้นแบบแขนฟลิปช่องทางเดียว', 0, 'EACH', ''),
('SST', 'EPB', 'Exit Button Stainless', 0, 'EACH', ''),
('SST', 'EPS', 'Emergency power supply', 0, 'EACH', ''),
('SST', 'EPS100', 'Emergency Door Opening Device', 0, 'EACH', ''),
('SST', 'EPS1000', 'SALTO Emergency Device', 0, 'EACH', ''),
('SST', 'ES', 'Electric Strike for Panic', 0, 'EACH', ''),
('SST', 'ESD92UIC', 'SALTO Energy Saver ESD9000 Online', 0, 'EACH', ''),
('SST', 'F2000N-SET', 'ชุดมอเตอร์ประตูรีโมท รุ่น F2000', 0, 'ชุด', ''),
('SST', 'G9A1', 'Electronic cylinder', 0, 'EACH', ''),
('SST', 'G9A1100N00P', 'SALTO GEO Cylinder Mifare Australia', 0, 'EACH', ''),
('SST', 'G9B31', 'G9B31 Dead Bolt', 0, 'EACH', ''),
('SST', 'G9E1135NOOC', 'GEO Half cylinder Euro profile Electronic', 9300, 'EACH', ''),
('SST', 'G9E1135NOOP', 'GEO Half cylinder Euro profile Electronic', 9500, 'EACH', ''),
('SST', 'G9E2130S30CS', 'SALTO GEO Eeuro Profile Cylinder Romo', 0, 'EACH', ''),
('SST', 'G9E2135S35C', 'GEO Cylinder SALTO Mifare', 0, 'EACH', ''),
('SST', 'G9E2135S35P', 'GEO Cilindro SALTO Mifare', 0, 'EACH', ''),
('SST', 'G9E2135S35PP', 'GEO Mortise profile electronic cylinder E', 9800, 'EACH', ''),
('SST', 'G9E2230S30CS', 'SALTO GEO ELECTRONIC CULINDER', 17800, 'Unit', ''),
('SST', 'G9E32', 'SALTO GEO Electr. Euro profile', 15500, 'EACH', ''),
('SST', 'G9E9130N00C', 'SALTO GEO Half cylinder Electronic cyl', 0, 'EACH', ''),
('SST', 'G9M1129N00C', 'GEO Euro profilfe electronic cylinder St', 0, 'EACH', ''),
('SST', 'G9P21', 'PADLOCK 48MM WIRELESS', 19400, 'Unit', ''),
('SST', 'GATEWAY2', 'SALTO Wireless gateway for wireless 2 s', 9600, 'Unit', ''),
('SST', 'GATEWAY3', 'SALTO Wireless gateway for wireless 2 s', 0, 'EACH', ''),
('SST', 'GL1', 'SECUITRON GATEWAY', 0, 'EACH', ''),
('SST', 'GLEMLBRACK', 'BRACKET MAGNETIC LOCK FOR GLAS', 0, 'EACH', ''),
('SST', 'H06', 'Handle IM Finish U Handle', 0, 'EACH', ''),
('SST', 'HAFMOBS55', 'Mortise Lock Entrance BS 55', 0, 'EACH', ''),
('SST', 'HAMSEXC', 'RW HAMS Excellence.', 0, 'EACH', ''),
('SST', 'HD20KD', 'Door Cencer', 0, 'EACH', ''),
('SST', 'HID-045515', 'ECO YMCKO Refill Ribbon', 0, 'Unit', ''),
('SST', 'HID-081754', 'UltraCard 30 mil cards', 0, 'CARD', ''),
('SST', 'HID-086177', 'Cleaning Kit', 0, 'Unit', ''),
('SST', 'HID1326', 'HID 1326', 0, 'CARD', ''),
('SST', 'HID1386', 'HID 1386', 0, 'CARD', ''),
('SST', 'HID1431', 'HID 1431', 0, 'CARD', ''),
('SST', 'HID2000', 'HID 2000', 0, 'CARD', ''),
('SST', 'HID5455', 'HID Reader 5455', 0, 'EACH', ''),
('SST', 'IBPSR', 'Programming Card', 0, 'EACH', ''),
('SST', 'IBUSB', 'iButton User', 0, 'EACH', ''),
('SST', 'INS', 'Cylinder Installation', 0, 'EACH', ''),
('SST', 'IPC-B122-APF2', 'Bullet 2M, IP67, 2.8mm', 0, 'EACH', ''),
('SST', 'IPC-B122-APF4', 'Bullet 2M, IP67, 4mm', 0, 'EACH', ''),
('SST', 'IPC-T122-APF2', 'Dome 2M, IP67, 2.8mm', 0, 'EACH', ''),
('SST', 'IQ22B', 'SALTO IQ 2.0 POE', 0, 'EACH', ''),
('SST', 'IQ22W300CLP', 'SALTO IQ 2.0 POE', 0, 'EACH', ''),
('SST', 'IQ22W300KS', 'SALTO IQ2.0 PoE', 0, 'EACH', ''),
('SST', 'IQ22W300KS-T', 'SALTO KS IQ2.0', 0, 'EACH', ''),
('SST', 'ISOCARD', 'Card with Preprint School Layout', 0, 'CARD', ''),
('SST', 'Key', 'key Switch', 0, 'EACH', ''),
('SST', 'KPB031M', 'SALTO XS4 Panic bar Kit for versions of', 0, 'EACH', ''),
('SST', 'KPB031MW', 'STAINLESS STEEL FINISH', 12000, 'Unit', ''),
('SST', 'KPP33IM', 'SALTO XS4 Panic Bar for versions wire', 0, 'EACH', ''),
('SST', 'KS', 'Key Swithc', 810, 'Unit', ''),
('SST', 'LA1T1570A201', 'SALTO ANSI mortise lock with latch and c', 0, 'EACH', ''),
('SST', 'LA1T1770A741I', 'SALTO AElement ANSI mortise lock', 0, 'EACH', ''),
('SST', 'Lanyard15mm', 'STRAPCARD LANYARD 15 MM', 0, 'EACH', ''),
('SST', 'LCE8P', 'Strike Plate', 120, 'EACH', ''),
('SST', 'LD51C', 'LD51C Dead Bolt', 0, 'EACH', ''),
('SST', 'LE7505555R02', 'SALTO MORTICE', 0, 'EACH', ''),
('SST', 'LE7S', 'Mortice Lock', 0, 'EACH', ''),
('SST', 'LE7S0555R421', 'XS4 EURO Mortise Lock', 0, 'EACH', ''),
('SST', 'LE7S0560R021I', 'SALTO MORTICE LOCK', 0, 'EACH', ''),
('SST', 'LE7S0560R4211', 'XS4 EURO Mortise Lock', 0, 'EACH', ''),
('SST', 'LE7S0565R421', 'XS4 EURO Mortise Lock', 0, 'EACH', ''),
('SST', 'LE7S1565R431', 'Salto Din Mortise Lock', 0, 'EACH', ''),
('SST', 'LE8P02', 'Mortise Lock case', 0, 'Unit', ''),
('SST', 'LE8P0260', 'SALTO European mortise lock with proj', 0, 'EACH', ''),
('SST', 'LE8P0260C001', 'XS4 Euro Mortise Lock', 0, 'EACH', ''),
('SST', 'LE8P0260R', 'XS4 EURO Mortise Lock', 0, 'EACH', ''),
('SST', 'LE8P0260R301', 'XS4 EURO Mortise Lock', 0, 'EACH', ''),
('SST', 'LE8P1260C311', 'SALTO European mortise lock with proj', 0, 'EACH', ''),
('SST', 'LE9W3140C401', 'XS4 EURO Narrow Mortice Lock+strike P', 0, 'Unit', ''),
('SST', 'LP101', 'Loop single', 0, 'EACH', ''),
('SST', 'LZB600', 'L&Z Bracket', 0, 'EACH', ''),
('SST', 'LZ-BRACKET', 'LZ Bracket', 0, 'EACH', ''),
('SST', 'M6000', 'Magnetic Lock 600Lbs w/ LZ Bracket', 0, 'Unit', ''),
('SST', 'Magnetic', 'Magnetic Lock', 0, 'EACH', ''),
('SST', 'MF', 'Mifare Card', 0, 'CARD', ''),
('SST', 'MFISO', 'Mifare 1K ISO Card 50/Pack (white card)', 0, 'Pack', ''),
('SST', 'MFTAG', 'MIFARE TAG SILICON', 0, 'CARD', ''),
('SST', 'MG', 'Magnetic Lock 600lbs with LED', 0, 'EACH', '');

INSERT INTO public.products (company, product_code, name, price, unit, barcode) VALUES
('SST', 'Mifare-Fob', 'Mifare Fob', 0, 'Pack', ''),
('SST', 'Mortise3109', 'YALE Mortise 3109', 0, 'EACH', ''),
('SST', 'MortiseLock', 'Mortise Lock', 0, 'Unit', ''),
('SST', 'NBE2130S30CS', 'NEO Cylinder EURO/IP66', 0, 'EACH', ''),
('SST', 'NBJ1100N00CS', 'NBJ1100N00CSBN', 0, 'EACH', ''),
('SST', 'NHAEXC', 'HAMS Excellence SQL software', 0, 'EACH', ''),
('SST', 'NME1135N00C', 'NEO Cylinder, Half Cylinder, 35mm', 0, 'EACH', ''),
('SST', 'NME2130S20C', 'SALTO NEO Cylinder', 0, 'EACH', ''),
('SST', 'NME2132S30C', 'Salto Neo Euro Cylinder', 0, 'EACH', ''),
('SST', 'NME2140S40N', 'Neo Cylinder Euro', 0, 'EACH', ''),
('SST', 'NMP4P60150C', 'SALTO NEOXX PANLOCK GRADE4, MIF', 0, 'EACH', ''),
('SST', 'NODE2', 'SALTO Node', 0, 'EACH', ''),
('SST', 'NODE3', 'SALTO Node', 0, 'EACH', ''),
('SST', 'NPAEXEC', 'RW Pro Access Excellence SQL. Upto -4', 0, 'EACH', ''),
('SST', 'NVR-21652-F16', 'NVR 16 Channel PОЕ', 0, 'EACH', ''),
('SST', 'OPT-0033', 'SPACE Wireless Bluenet/ Per Door', 0, 'EACH', ''),
('SST', 'Other', 'Other', 0, 'EACH', ''),
('SST', 'PB', 'Exit Button', 0, 'EACH', ''),
('SST', 'PBF1100915', 'RIM PANIC BAR DEVICES', 27000, 'Unit', ''),
('SST', 'PBF1100915IM', 'SALTO RIM Panic Bar Device. Stainless s', 27000, 'Unit', ''),
('SST', 'PB-NoTouch', 'Exit', 0, 'EACH', ''),
('SST', 'PCB535Y', 'Main Board for Barrier 535', 0, 'EACH', ''),
('SST', 'PCB-535Y', 'Spare part Control Board', 0, 'EACH', ''),
('SST', 'PCD04KKS', 'SALTO KS MAINTENANCE CARD', 0, 'EACH', ''),
('SST', 'PCM01KB', 'Salto Card', 0, 'EACH', ''),
('SST', 'PCM01KB-50', 'Proximity card Mifare 1K white', 0, 'Pack', ''),
('SST', 'PCMPS', 'Salto Mifare Programming', 0, 'CARD', ''),
('SST', 'PCMULCB', 'Proximity Card Ultralight C Blank', 0, 'CARD', ''),
('SST', 'PCMULCB-50', 'Contactless smart card Mifare Ultyralight', 0, 'EACH', ''),
('SST', 'PFD04KRRE-5', 'Proximity fob Desfire 4K RED', 0, 'EACH', ''),
('SST', 'PFD04KSGRE-5', 'Proximity fob Desfire 4K', 0, 'EACH', ''),
('SST', 'PFM01KB10', 'SALTO Keyfob', 0, 'Pack', ''),
('SST', 'PLR001', 'Plastic Reader Plate', 0, 'EACH', ''),
('SST', 'PN6050', 'Panic Bar NO16050', 0, 'EACH', ''),
('SST', 'PMC01', 'Salto Card', 0, 'CARD', ''),
('SST', 'PPD800', 'SALTO Portable Programming Device', 0, 'EACH', ''),
('SST', 'PR402', 'Control Unit with Coverter', 0, 'EACH', ''),
('SST', 'PROACCESS', 'Proaccess Software Service', 0, 'EACH', ''),
('SST', 'PWS', 'Power Supply 12VDC 3A', 0, 'Unit', ''),
('SST', 'PWS12WB', 'POWER SUPPLY 12VDC WITH BATTERY', 0, 'EACH', ''),
('SST', 'PWVG301', 'Single Channel Loop Vehicle Detector', 0, 'EACH', ''),
('SST', 'R1SIRIM', 'Salto L Handle for Element handle set', 0, 'EACH', ''),
('SST', 'R3SWRIM081', 'SALTO W handle for AElement handle se', 0, 'EACH', ''),
('SST', 'RE01', 'Remote', 0, 'EACH', ''),
('SST', 'Refillable', 'Refillable Cartridge', 0, 'Unit', ''),
('SST', 'Relay', 'Timer Relay', 0, 'EACH', ''),
('SST', 'Remote', 'Remote Control', 0, 'EACH', ''),
('SST', 'RENODE', 'SALTO Wireless node kit', 0, 'EACH', ''),
('SST', 'RFDTCT', 'Door Contact', 235, 'EACH', ''),
('SST', 'RFDTCTS30W0', 'SALTO Door Detector', 0, 'EACH', ''),
('SST', 'RFM-800', 'Spare Part Bluetooth Reader', 0, 'EACH', ''),
('SST', 'RFMODULEWO', 'SALTO Wireless Antenna Kit', 3000, 'EACH', ''),
('SST', 'RFNODE3', 'Salto Wireless Node RF3', 0, 'EACH', ''),
('SST', 'RL01', 'Relay Board', 0, 'EACH', ''),
('SST', 'S02-01', 'Magnetic Lock 1200Lbs', 0, 'EACH', ''),
('SST', 'S02-LZ', 'L&Z Breacket For S02', 0, 'EACH', ''),
('SST', 'SaltoCard', 'Salto Card', 0, 'CARD', ''),
('SST', 'SALTOdoor', 'SALTO Door Contact for xs4 (DC)', 0, 'EACH', ''),
('SST', 'SE9W3140N252', 'EURO Narrow Mortiselock + Strike Plate', 0, 'EACH', ''),
('SST', 'SL01', 'Sliding Mortise Lock', 0, 'EACH', ''),
('SST', 'SLA-101', 'Automatice Sliding Door', 0, 'EACH', ''),
('SST', 'SP0015', 'PPF Emergency Cable', 0, 'EACH', ''),
('SST', 'SP00200', 'Cylinder Adaptor PZ', 0, 'EACH', ''),
('SST', 'SP00261', 'PRIVACY CIRCUIT', 0, 'EACH', ''),
('SST', 'SP00790W40E0', 'XS4 Origimal Inside Cover Plate', 0, 'EACH', ''),
('SST', 'SP01058', 'มือจับ Salto', 0, 'EACH', ''),
('SST', 'SP220334', 'BATTERIES SUPPORT LR03', 0, 'EACH', ''),
('SST', 'SP220436-C', 'ESD Spare part', 0, 'EACH', ''),
('SST', 'SP220444', 'Outdoor Kit (Pack of 6)', 0, 'Pack', ''),
('SST', 'SP220764', 'Removeable Tool', 0, 'EACH', ''),
('SST', 'SP221213', 'SP221213-16-U8NE Outside Handle Bla', 0, 'EACH', ''),
('SST', 'SP225393', 'Aelemet Fusion Control', 0, 'EACH', ''),
('SST', 'SP225542', 'Key for NEO Knob', 0, 'EACH', ''),
('SST', 'SPAOPT17', 'DATABASE SYNCHRONIZE', 0, 'EACH', ''),
('SST', 'SPACEOPT-003', 'SALTO PROACCESS SPACE SOFTWARE', 0, 'EACH', ''),
('SST', 'SPACE-OPT-00', 'SPACE WIRELESS BLUENET/ Per Door', 0, 'EACH', ''),
('SST', 'SPAIDSYS', 'SALTO Software', 0, 'EACH', ''),
('SST', 'SPAONLINE', 'SALTO ProAccess SPACE software - Onl', 0, 'EACH', ''),
('SST', 'SPAOP121', 'WIRELESS INTERFACE', 0, 'EACH', ''),
('SST', 'SPAPART', 'SALTO PROACCESS SPACE SOFTWAR', 75000, 'EACH', ''),
('SST', 'SPC-1MF', 'SALTO CARD SPC-1MF', 0, 'CARD', ''),
('SST', 'SPKREMKITG', 'SALTO RF net Maintenance Kit', 0, 'EACH', ''),
('SST', 'ST4000VX016', 'Skyhawk Survelliance HDD 4TB', 0, 'EACH', ''),
('SST', 'Stainlessplate', 'STAINLESS PLAte', 0, 'EACH', ''),
('SST', 'SWGB231', 'Automatic Barrier 6m แขนพับ', 0, 'EACH', ''),
('SST', 'SWGB232', 'Automatic Barrier 6m. แขนตรง', 0, 'EACH', ''),
('SST', 'SWLP02', 'Loop 2 Chanal', 0, 'EACH', ''),
('SST', 'TE010H30NM', 'Privacy and Thumbrun', 0, 'EACH', ''),
('SST', 'TL-SG105', 'Network Switch 4 CH', 0, 'EACH', ''),
('SST', 'TUPB', 'Touchless Exit Button', 0, 'CARD', ''),
('SST', 'U600', 'U Bracket', 0, 'EACH', ''),
('SST', 'UBOX900', 'Updater Kit', 0, 'EACH', ''),
('SST', 'UPS', 'UPS 15000 VA', 14250, 'Unit', ''),
('SST', 'VOUCHKS-S', 'SALTO KS SMALL', 0, 'EACH', ''),
('SST', 'Vouchks-xxl', 'Vouchks-xxl', 0, 'EACH', ''),
('SST', 'VP1-3', 'Lockset with Lever Handle Stainless', 0, 'EACH', ''),
('SST', 'VP1-6', 'Lockwood Mortise Lock', 0, 'EACH', ''),
('SST', 'VP1-9', 'Mortice Lock 60 mm.', 0, 'EACH', ''),
('SST', 'VP1-9SET', 'Lockset with Lever handle Stainless', 0, 'ชุด', ''),
('SST', 'WD43PURZ', 'HD 4TB for CCTV', 0, 'EACH', '');

INSERT INTO public.products (company, product_code, name, price, unit, barcode) VALUES
('SST', 'WRD9000', 'SALTO XS4 2.0 Design Wall Reader Pro', 0, 'EACH', ''),
('SST', 'WRD90E4ABY', 'SALTO WALL READER Black Finish', 0, 'EACH', ''),
('SST', 'WRD90E4BY', 'WR4000 Mifare CLAY Black', 0, 'EACH', ''),
('SST', 'WRDB04SB', 'Salto Wall Reder White', 0, 'EACH', ''),
('SST', 'WRDBOE0', 'SALTO XS4 2.0 Wall Reader DESfire', 0, 'Unit', ''),
('SST', 'WRDB0E4B', 'Salto Wall Reader', 0, 'EACH', ''),
('SST', 'WRDB0E4BK', 'Salto BLE+Keypad Wall Reader', 0, 'EACH', ''),
('SST', 'WRDB0E4BKY', 'SALTO WALL READER Black Finish', 0, 'EACH', ''),
('SST', 'WRDB0E4W', 'SALTO Reader', 0, 'EACH', ''),
('SST', 'WRDB0M4B', 'SALTO WALL READER MULLION', 0, 'EACH', ''),
('SST', 'WRDBOM4W', 'SALTO XS4 2.0 Mullion Wall Reader', 0, 'EACH', ''),
('SST', 'WRDM0M4B', 'Salto Design XS-Wall Reader', 0, 'EACH', ''),
('SST', 'WRM9001', 'SALTO Modula Wall Reader Mifare/DE', 0, 'EACH', ''),
('SST', 'WRM9001FF', 'SALTO Modular Wall Reader', 0, 'EACH', ''),
('SST', 'WRM9001FS', 'SALTO Modular Wall Reader', 0, 'EACH', ''),
('SST', 'WRMBL1', 'SALTO Base for flush mounting', 0, 'EACH', ''),
('SST', 'WT-Y02', 'Wing Turstile (Left, Right) Safety Mode', 89790, 'Unit', ''),
('SST', 'WT-Y02A', 'Wing Turnstile (Center) Safety Mode', 116030, 'Unit', ''),
('SST', 'Y591CTCS', 'Lockwood Aluminium Sliding Lock', 0, 'EACH', ''),
('SST', 'YDM3109', 'Yale Digital Lock YDM3109', 0, 'EACH', ''),
('SST', 'YDM7116A', 'YDM7116A', 0, 'EACH', ''),
('SST', 'ZLS800', 'Bracket for Magnetic Lock', 0, 'EACH', ''),
('SST', 'SP210233', 'Wireless Battery Support LR03', 1100, 'EACH', '');

